/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountSecurityRouteImport } from './routes/account.security'
import { Route as AccountPrivacyRouteImport } from './routes/account.privacy'
import { Route as AccountPersonalRouteImport } from './routes/account.personal'
import { Route as AccountLoopRouteImport } from './routes/account.loop'
import { Route as AccountRegionalRouteImport } from './routes/account.regional'
import { Route as AccountTrustRouteImport } from './routes/account.trust'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AccountRoute,
} as any)
const AccountPrivacyRoute = AccountPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AccountRoute,
} as any)
const AccountPersonalRoute = AccountPersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => AccountRoute,
} as any)
const AccountLoopRoute = AccountLoopRouteImport.update({
  id: '/loop',
  path: '/loop',
  getParentRoute: () => AccountRoute,
} as any)
const AccountRegionalRoute = AccountRegionalRouteImport.update({
  id: '/regional',
  path: '/regional',
  getParentRoute: () => AccountRoute,
} as any)
const AccountTrustRoute = AccountTrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => AccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/welcome': typeof WelcomeRoute
  '/account/personal': typeof AccountPersonalRoute
  '/account/privacy': typeof AccountPrivacyRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/loop': typeof AccountLoopRoute
  '/account/regional': typeof AccountRegionalRoute
  '/account/trust': typeof AccountTrustRoute
  '/account/': typeof AccountIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/welcome': typeof WelcomeRoute
  '/account/personal': typeof AccountPersonalRoute
  '/account/privacy': typeof AccountPrivacyRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/loop': typeof AccountLoopRoute
  '/account/regional': typeof AccountRegionalRoute
  '/account/trust': typeof AccountTrustRoute
  '/account': typeof AccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/welcome': typeof WelcomeRoute
  '/account/personal': typeof AccountPersonalRoute
  '/account/privacy': typeof AccountPrivacyRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/loop': typeof AccountLoopRoute
  '/account/regional': typeof AccountRegionalRoute
  '/account/trust': typeof AccountTrustRoute
  '/account/': typeof AccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/login'
    | '/sitemap.xml'
    | '/welcome'
    | '/account/personal'
    | '/account/privacy'
    | '/account/security'
    | '/account/loop'
    | '/account/regional'
    | '/account/trust'
    | '/account/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/welcome'
    | '/account/personal'
    | '/account/privacy'
    | '/account/security'
    | '/account/loop'
    | '/account/regional'
    | '/account/trust'
    | '/account'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/login'
    | '/sitemap.xml'
    | '/welcome'
    | '/account/personal'
    | '/account/privacy'
    | '/account/security'
    | '/account/loop'
    | '/account/regional'
    | '/account/trust'
    | '/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/security': {
      id: '/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/privacy': {
      id: '/account/privacy'
      path: '/privacy'
      fullPath: '/account/privacy'
      preLoaderRoute: typeof AccountPrivacyRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/personal': {
      id: '/account/personal'
      path: '/personal'
      fullPath: '/account/personal'
      preLoaderRoute: typeof AccountPersonalRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/loop': {
      id: '/account/loop'
      path: '/loop'
      fullPath: '/account/loop'
      preLoaderRoute: typeof AccountLoopRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/regional': {
      id: '/account/regional'
      path: '/regional'
      fullPath: '/account/regional'
      preLoaderRoute: typeof AccountRegionalRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/trust': {
      id: '/account/trust'
      path: '/trust'
      fullPath: '/account/trust'
      preLoaderRoute: typeof AccountTrustRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AccountRouteChildren {
  AccountPersonalRoute: typeof AccountPersonalRoute
  AccountPrivacyRoute: typeof AccountPrivacyRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AccountLoopRoute: typeof AccountLoopRoute
  AccountRegionalRoute: typeof AccountRegionalRoute
  AccountTrustRoute: typeof AccountTrustRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountPersonalRoute: AccountPersonalRoute,
  AccountPrivacyRoute: AccountPrivacyRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AccountLoopRoute: AccountLoopRoute,
  AccountRegionalRoute: AccountRegionalRoute,
  AccountTrustRoute: AccountTrustRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
